### ISSUE TITLE
Support for perform_async/0?

### ISSUE THREAD

**Issue by krainboltgreene** [opt-elixir/faktory_worker#97]
I have jobs that have no arguments, so it seems weird that I'm forced to do `Processor.Jobs.PullMarketPrices.perform_async([])`.

**Comment by swelham** [comment]
Yes, I agree it's weird having to pass in an empty list in this case. I think having a `perform_async/0` function makes sense with the caveat that it won't be able to accept an `opts` keyword list in the same way the current version does since this will create two versions of `perform_async/1`.

This would mean when opts are required an empty list would still need to be specified. For example, we would have these variations.
```elixir
Job.perform_async()
Job.perform_async([], opts)

Job.perform_async(some_job)
Job.perform_async(some_job, opts)
```

**Comment by krainboltgreene** [comment]
Ahhh
